### ISSUE TITLE
Question: why avoid apple git?

### ISSUE THREAD

**Issue by seasonedfish** [DesantBucie/korny#17]
In your readme, you have,

> git (avoid apple crappy one, install one from nix or brew)

This is the first time I've been advised to avoid Apple git. I'm curious, why should I avoid it?

**Comment by DesantBucie** [comment]
It's because when i was using Oh-my-zsh, which checks for update every session(korny doesn't btw), i would get 10 or more second freeze on terminal start with xcode-something command.

I tried to solve this by "accepting license" command, but it didn't help. This actually pushed me to drop using oh-my-zsh. After further "investigation" it happend to be git version that I installed via apple gui manager. Then after i overwritten it with nix or brew version it didn't had this type of problem.

I still sometimes face this problem when running things installed from apple like clang, although it mostly happened after power offs, which i don't do now very often

**Comment by seasonedfish** [comment]
Ah I see, thanks!
